-- Seed eje PRODUCTO real del LIMS (GGRUPO/GRUPO_ELEM). Idempotente. tenant IDIC.
INSERT INTO gran_grupo (tenant_id, codigo, nombre)
SELECT t.id, v.codigo, v.nombre FROM tenant t, (VALUES
  ('E','Explosivos Prod. Nacional'),
  ('P','Productos químicos'),
  ('A','Armas y accesorios'),
  ('M','Municiones y accesorios'),
  ('F','Artificios'),
  ('IDIC','Elementos IDIC'),
  ('DMT','DMT'),
  ('E-I','Explosivos importación'),
  ('EL','Electrónica'),
  ('PI','Pinturas'),
  ('BPCH','BPCH'),
  ('AU','Carabineros de Chile')
) AS v(codigo,nombre) WHERE t.codigo='IDIC' ON CONFLICT (tenant_id,codigo) DO NOTHING;

-- Grupos bajo su Gran Grupo (por código de gran grupo)
INSERT INTO grupo (tenant_id, gran_grupo_id, cgrupo, nombre)
SELECT t.id, gg.id, v.cgrupo, v.nombre
FROM tenant t JOIN (VALUES
  ('E','1','Dinamitas'),
  ('E','2','Sustancias químicas'),
  ('E','3','Nitrocarbonitratos'),
  ('E','4','Explosivos acuosos'),
  ('E','5','Accesorios'),
  ('A','27','Arma de Fantasia'),
  ('E','7','Detonadores'),
  ('F','8','Fuegos artificiales'),
  ('IDIC','9','Grupo IDIC'),
  ('A','29','Cañón industrial Carga única'),
  ('P','12','Importación'),
  ('E','11','Matrices'),
  ('DMT','20','Lab. Calibración Área Mecánica'),
  ('DMT','22','Lab. Control Dimensional'),
  ('E-I','73','Dinamitas'),
  ('A','31','Carabina 1 Cñ. de Repetición'),
  ('A','33','Escopeta 1 Cñ Carga única   ( C.U.)'),
  ('A','35','Escopeta 1 Cñ Semiautomática ( S.A.)'),
  ('A','37','Escopeta 2 Cñs. Yuxtapuestos   ( Y.P.)'),
  ('A','39','Sub Ametralladora Semiautomática'),
  ('A','41','Escopeta Avancarga'),
  ('A','43','Fusil Carga única'),
  ('A','45','Fusil Semiautomático'),
  ('A','47','Pistola Avancarga 2 Cñs. Superpuestos'),
  ('A','49','Pistola Carga única de Concurso'),
  ('A','51','Pistola Semiautomática de Concurso'),
  ('A','53','Pistolete Carga única de Caza'),
  ('A','55','Revólver 2 Cñ Acción Simple'),
  ('A','57','Revólver 4 Cñ Acción Simple'),
  ('A','59','Revólver 6 Cñs Acción Simple'),
  ('A','61','Revólver Doble Acción'),
  ('A','63','Rifle Carga única'),
  ('A','65','Rifle de Repetición'),
  ('A','67','Sub Ametralladora automática'),
  ('A','69','Repuestos y accesorios'),
  ('M','71','Importaciones'),
  ('E-I','75','Accesorios'),
  ('E-I','77','Explosivos acuosos'),
  ('A','79','Armas de internación'),
  ('F','81','Elementos salvataje marítimo'),
  ('E-I','84','Explosivos'),
  ('EL','86','Optrónica'),
  ('EL','88','Ingeniería'),
  ('A','90','Revólver Acción Simple'),
  ('M','91','Producción nacional'),
  ('M','93','01-Cartuchos con garganta'),
  ('M','95','03-Cartuchos culote reforzado'),
  ('M','97','05-Cartuchos de percusión anular'),
  ('M','99','07-Cartuchos de plomo'),
  ('M','101','09-Cartuchos granalla'),
  ('M','102','VAINILLAS'),
  ('E','215','Plasma'),
  ('E-I','106','Altos explosivos'),
  ('EL','107','Simuladores'),
  ('A','109','Pistolete 1 Cñ. Avancarga'),
  ('PI','110','Microesferas'),
  ('PI','112','Baja concentración'),
  ('PI','113','Atóxica'),
  ('PI','114','Hidrorepelente'),
  ('PI','115','Decorativa'),
  ('PI','116','Industrial'),
  ('PI','117','Muebles'),
  ('PI','118','Cilindros'),
  ('PI','119','Retardantes al fuego'),
  ('PI','120','Varios'),
  ('A','121','Revólver 2 Cñs Avancarga'),
  ('EL','122','Óptica'),
  ('A','123','Revólver 2 Cñs Superpuestos'),
  ('EL','124','Calzado'),
  ('F','125','Elementos fumígenos'),
  ('A','126','Rifle de Repetición Lanza Dardo'),
  ('A','127','Fusil 2 Cñs. Yuxtapuestos'),
  ('F','128','Iniciadores'),
  ('A','129','revólver fogueo'),
  ('A','130','Pistolete 2 Cñs. Superpuestos'),
  ('A','131','Revólver 2 Cñs Yuxtapuestos'),
  ('A','216','Escopeta 2 Cñs. (Y/P)  1 Liso 1 Rayado'),
  ('A','135','Pistolete Carga Unica'),
  ('A','136','Maquina recargadora'),
  ('EL','137','Radar'),
  ('A','138','Fusil 2 Cñs. Superpuestos'),
  ('F','139','Fracturador de rocas'),
  ('A','140','Pistolete 2 Cñs. Yuxtapuestos'),
  ('A','142','Escopeta Avancarga 2 Cñs. Yuxtapuestos'),
  ('A','143','Pistola 4 Cñ Acción Simple'),
  ('A','144','Pistolete avancarga 2 Cñs Yuxtapuestos'),
  ('A','145','Rifle de Repeticion Concurso'),
  ('A','147','Carabina de Avancarga'),
  ('E-I','148','Explosivos en tránsito'),
  ('A','150','Pistola 1Cñ Carga única'),
  ('A','152','Pistolete de Repetición'),
  ('A','154','Revólver 4 Cñ  Doble Acción'),
  ('A','155','Revólver 6 Cñs  Doble Acción'),
  ('A','156','Revólver 6 Cñs Avancarga'),
  ('A','157','Revólver 4 Cñ Avancarga'),
  ('A','158','Pistolete 2 Cñs. Yuxtapuestos de caza'),
  ('A','159','Fusil de Repetición Concurso'),
  ('A','161','Pistolete 2 Cñs. Superpuestos de Caza'),
  ('A','162','Pistolete Avancarga'),
  ('A','163','Revólver Acción Simple de Concurso'),
  ('A','165','Pistolete Avancarga de Duelo'),
  ('E','170','Municiones'),
  ('A','173','Fusil  Avancarga de Repetición'),
  ('A','174','Revólver 1 Cñ Doble Acccion Carga única'),
  ('F','178','Antigranizos'),
  ('A','192','Conversión para Pistola'),
  ('A','13','Base de pruebas'),
  ('A','28','Cañón control de Avalanchas Carga única'),
  ('A','30','Carabina Carga única'),
  ('A','32','Carabina Semiautomática'),
  ('A','34','Escopeta 1 Cñ de Repetición   ( R.P.T.)'),
  ('A','36','Escopeta 2 Cñs. Superpuestos   ( S.P.)'),
  ('E','19','Iniciadores / Reforzadores'),
  ('DMT','21','Lab. Calibración Área Eléctrica'),
  ('DMT','23','Lab. Custodio Patrón Nacional - Fuerza'),
  ('A','76','Revólver 1 Cñ Acción Simple carga única'),
  ('A','26','Arcabuz de Avancarga'),
  ('E','68','Explosivos'),
  ('A','40','Escopeta 3 Cñs. 2 Lisos 1 Rayado'),
  ('A','42','Fusil de Repeticion'),
  ('A','44','Fusil de Avancarga'),
  ('A','46','Pistola  Automatica'),
  ('A','48','Pistola Avancarga'),
  ('A','50','Pistola Semiautomática Accion Simple'),
  ('A','52','Pistola Semiautomática Doble Accion'),
  ('A','54','Pistolete de Señales Carga única'),
  ('A','56','Revólver 3 Cñs Acción Simple'),
  ('A','58','Revólver 5 Cñ Acción Simple'),
  ('A','60','Revólver Avancarga'),
  ('A','62','Rifle Avancarga'),
  ('A','64','Rifle Carga única de Concurso'),
  ('A','66','Rifle Semiautomático'),
  ('A','72','Informes técnicos'),
  ('E-I','74','Detonadores'),
  ('E-I','217','Artificios'),
  ('M','105','Cartuchos industriales'),
  ('A','82','Pistolete 3 Cñs. Superpuestos'),
  ('F','83','Disuasivos'),
  ('EL','85','Comunicaciones'),
  ('EL','87','Seguridad'),
  ('E-I','89','Cartuchos Fragmentadores'),
  ('M','92','Base de pruebas'),
  ('M','94','02-Cartuchos pestaña externa'),
  ('M','96','04-Cartuchos para pistolas y revólveres'),
  ('M','98','06-Cartuchos para aparato industrial'),
  ('M','100','10-Cartuchos para otras armas'),
  ('M','103','Accesorios'),
  ('EL','108','Comando y Control'),
  ('PI','111','Tráfico'),
  ('M','132','11-Calibres sin vainilla'),
  ('M','134','002-Fulminantes'),
  ('A','141','Revólver 5 Cñs Avancarga'),
  ('A','146','Pistola Carga Unica'),
  ('A','149','Fusil Lanza arpón'),
  ('A','151','Pistola 2 Cñ Superpuestos'),
  ('A','153','Revólver 2 Cñ Superpuestos Avancarga'),
  ('A','160','Escopeta 3 Cñs. 1 Liso 2 Rayados'),
  ('A','164','Revólver Doble Accion de Concurso'),
  ('A','166','Cañón carga única'),
  ('A','167','Fusil Carga única de Concurso'),
  ('A','168','Fusil Automático'),
  ('A','169','Pistolete avancarga 2 Cñs Superpuestos'),
  ('A','172','Ingenio para pruebas sísmicas'),
  ('A','175','Carabina de Repetición 2 Cñs. 1 avanc.'),
  ('M','181','Cartucho Para Fusil de Reglaje Cñ. 106'),
  ('A','184','Revólver Doble Accion Carga única'),
  ('A','186','Electroshock'),
  ('M','188','Electroshock'),
  ('BPCH','190','Investigación / peritaje / informes técnicos'),
  ('A','191','Revólver 2 Cñs 1 Avancarga'),
  ('A','193','Lanzador Simple de Proyectiles'),
  ('EL','195','Area Electrónica'),
  ('M','196','Vainillas semi metalicas sin capsular'),
  ('A','197','Pistola para Sacrificio de Animales'),
  ('AU','198','Carabineros de Chile'),
  ('AU','199','Autoridad Fiscalizadora'),
  ('BPCH','201','Asesoría Técnica'),
  ('A','202','Lanzador de Granada'),
  ('M','203','Vainillas metalicas sin capsular'),
  ('E','212','Cartuchos industriales'),
  ('E','206','Artificios Pirotécnicos'),
  ('A','207','Carabina 2 Cñ Superpuestos'),
  ('BPCH','208','Reunion de Coordinación Empresas'),
  ('BPCH','209','Retiro de muestras'),
  ('A','211','Replica de Arma'),
  ('E-I','213','Matrices'),
  ('E','218','Sistemas de iniciación'),
  ('E','219','Sustancias tóxicas'),
  ('E-I','220','Municiones Iluminantes'),
  ('E-I','221','Armas (Prueba)'),
  ('A','222','Dispositivo de Retención'),
  ('A','224','Pistola a Fogueo Semiautomatca Doble Acción'),
  ('A','225','Pistola a Fogueo Semiautomtica Acción Simple'),
  ('A','227','Revolver a Fogueo Acción Doble'),
  ('A','185','Ingenio atrapa aves'),
  ('A','187','Gas Disuasivo'),
  ('M','189','Gas Disuasivo'),
  ('E','182','Inspección en Planta'),
  ('M','194','CARTUCHERIA ESPECIAL (no C.I.P.)'),
  ('AU','200','Autoridad Fiscalizadora'),
  ('M','204','Cartuchos fogueo'),
  ('E','210','Toma de muestras'),
  ('E-I','214','Productos químicos'),
  ('M','223','Informes Técnicos'),
  ('A','226','Revolver a Fogueo Acción Simple'),
  ('A','229','No Cumple')
) AS v(gg_cod,cgrupo,nombre) ON TRUE
JOIN gran_grupo gg ON gg.tenant_id=t.id AND gg.codigo=v.gg_cod
WHERE t.codigo='IDIC' ON CONFLICT (tenant_id,gran_grupo_id,nombre) DO NOTHING;