-- ============================================================
-- SEED plantilla_informe · 117 plantillas reales del LIMS (PLANTILLAS.csv) · Aiuken
-- Idempotente. Requiere schema.sql (tabla plantilla_informe ya creada).
-- ============================================================
INSERT INTO plantilla_informe (tenant_id, repid, nombre, tipo, emision, archivo_ref)
SELECT t.id, v.repid, v.nombre, v.tipo, v.emision, v.archivo_ref
FROM tenant t, (VALUES
  ('BolAn','Boletin de Análisis con especificacion','BOLETIN','individual','Plantillas_Informes/Formatos/BOLETIN/'),
  ('CASPT','Calzado Seguridad Producto Terminado','BOLETIN','individual','Plantillas_Informes/Formatos/BOLETIN/'),
  ('CERT1','Boletin','BOLETIN','individual','Plantillas_Informes/Formatos/BOLETIN/'),
  ('CUEMI','Cueros Militares','BOLETIN','individual','Plantillas_Informes/Formatos/BOLETIN/'),
  ('CZSMP','Calzado seguridad Materias Primas','BOLETIN','individual','Plantillas_Informes/Formatos/BOLETIN/'),
  ('GSGMP','Guantes Seguridad Materias Primas','BOLETIN','individual','Plantillas_Informes/Formatos/BOLETIN/'),
  ('GSGPT','Guantes Seguridad Producto Terminado','BOLETIN','individual','Plantillas_Informes/Formatos/BOLETIN/'),
  ('IVC01','IVC','BOLETIN','individual','Plantillas_Informes/Formatos/BOLETIN/'),
  ('PLTXP','Boletin de Análisis Particular','BOLETIN','individual','Plantillas_Informes/Formatos/BOLETIN/'),
  ('PTNC','Boletín de Análisis con Especificación No Cumple','BOLETIN','individual','Plantillas_Informes/Formatos/BOLETIN/'),
  ('-','test','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('ASTEC','Certificado','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('ASTEC','Asistencia Técnica','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('ASTEC','Certificado de armas','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('CERT1','Certificado','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('NULL','test','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('PLAPI','Planilla de resultados','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('RECUN','Reconocimiento de cuño','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('RET2','CERTIFICADO COMBUSTION','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('SCCCC','SCC Certificado de Conformidad','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('SCCDG','SCC Certificado de Conformidad DGMN','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('SSTG2','Certifcado Velocidad (Lote a Lote)','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('SSTG2','CERTIFICADO VEL DETONACION','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('SSTG2','Certificado Velocidad (Lote a Lote)','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('SSTG3','Certificado Velocidad (Producción)','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('SSTG3','CERTIFICADO VEL DETONACION','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('SSTG3','EXPLOSIVOS VoD','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('SSTG3','Certificado Velocidad (Produccion)','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('SSTG4','Certificado Iniciadores','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('STGO1','Certificado de Retardos','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('STGO1','Certificado Tiempo Retardo (Internación)','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('STGO1','CERTIFICADO RETARDO','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('STGO1','TIEMPO RETARDO','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('STGO1','CertificadoTiempo de Retardo (Internacion)','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('VEL2','Certificado Velocidad (Solo Inspección Ocular)','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('VEL2','CERTIFICADO VEL DETONACION','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('VEL2','Certificado Velocidad (Solo Inspeccion Ocular)','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('cervt','Certificado tiempo combustion','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('cervt','CERTIFICADO COMÚN','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('cervt','CERTIFICADO COMUN','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('cervt','Certificado tiempo de combustion','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('i2bas','Certificado quimico','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('i2bas','I2BAS','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('i2bas','CERTIFICADO DE ANALISIS','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('i2bas','Certificado Quimico','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('inbas','CERTIFICADO DE CONTROL EXPLOSIVOS y QUIMICOS','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('inbas','Certificado de Control productos quimicos','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('inbas','INBAS','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('inbas','Certificado de control productos','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('inbas','Certificado Basico','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('inbas','Certificado','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('inbas','Cerificado básico','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('inbas','CERTIFICADO CONTROL EXPLOSIVOS y QUIMICOS','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('inbas','CERTIFICADO CONTROL EXPLOSIVOS y QUÍMICOS','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('inbas','Certificados de Control productos quimicos','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('punt','Punteras de Seguridad','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('ret2','Certificado Tiempo Retardo (Producción)','CERTIFICADO','conjunto','Plantillas_Informes/Formatos/CERTIFICADO/'),
  ('IFINN','Informe Ensayo con certificación INN','I.ENSAYO','conjunto','Plantillas_Informes/Formatos/IENSAYO/'),
  ('IFINN','Informe Ensayo  con certificación INN','I.ENSAYO','conjunto','Plantillas_Informes/Formatos/IENSAYO/'),
  ('IFINN','Informe de Ensayo con certificación INN','I.ENSAYO','conjunto','Plantillas_Informes/Formatos/IENSAYO/'),
  ('IFINN','Informe Ensayo INN','I.ENSAYO','conjunto','Plantillas_Informes/Formatos/IENSAYO/'),
  ('IFSL','Informe Ensayo sin certificación','I.ENSAYO','conjunto','Plantillas_Informes/Formatos/IENSAYO/'),
  ('IFSL','Informe Ensayo sin logo','I.ENSAYO','conjunto','Plantillas_Informes/Formatos/IENSAYO/'),
  ('IFSL','Informe de Ensayo  sin certificación','I.ENSAYO','conjunto','Plantillas_Informes/Formatos/IENSAYO/'),
  ('IFTUV','Informe Ensayo TUV','I.ENSAYO','conjunto','Plantillas_Informes/Formatos/IENSAYO/'),
  ('IFTUV','Informe de Ensayo con certificación TÜV','I.ENSAYO','conjunto','Plantillas_Informes/Formatos/IENSAYO/'),
  ('IFTUV','Informe Ensayo con certificación TÜV','I.ENSAYO','conjunto','Plantillas_Informes/Formatos/IENSAYO/'),
  ('IFTUV','Informe de ensayo con certificación TÜV','I.ENSAYO','conjunto','Plantillas_Informes/Formatos/IENSAYO/'),
  ('i2bas','Informe Basico','I.ENSAYO','conjunto','Plantillas_Informes/Formatos/IENSAYO/'),
  ('ASTEC','SCC Informe de Inspección','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('DAL01','Informe Propuesta','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('ESC','Informe Prendas Escuela','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('Inf3','Informe de Prendas (Sin V. Dim.)','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('InfT1','Informe Telas','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('InfT2','Informe de Prendas','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('SCCID','SCC Informe de Incumplimiento DGMN','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('SCCII','SCC Informe de Inspección','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('SCCIN','SCC Informe de Incumplimiento','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('dal1e','Informe formato EARFA/LP-020-2006 original','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('dal2e','Informe formato EARFA/LP-020-2006 Copia','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('dal2e','Informe formato EARFA/LP-020-2006 copia','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('i2bas','Informe Tecnico','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('inbas','Informe Técnico','I.TECNICO','individual','Plantillas_Informes/Formatos/ITECNICO/'),
  ('AQL1','I.V.C. Original AQL','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('AQL2','I.V.C. Copia AQL','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVC01','IVC','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVC01','I.V.C. Copia','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVC01','IVC Copia','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVC01','IVC Modelo A','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVC01','IVC copia','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVC01','I.V.C. MODELO A','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVC01','Certificado IVC','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVC2O','I.V.C. Original 2','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVCOR','Informe de Verifcación de Calidad','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVCTO','I.V.C. Tela Original','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVCTX','I.V.C. Original','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVCTX','I.V.C. MODELO T','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('IVCTX','IVC Modelo T','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('TXFAO','I.V.C. FF.AA. Original','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('YVC01','IVC original','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('YVC01','I.V.C. Original','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('YVC01','IVC Original','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('YVC01','Certificado IVC Original','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('ceci2','I.V.C. Copia Cecinas','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('cecin','I.V.C. Cecinas','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('cycpo','I.V.C. Prototipo Original','IVC','individual','Plantillas_Informes/Formatos/IVC/'),
  ('CERT1','Boletin','OTRO','conjunto','Plantillas_Informes/Formatos/OTRO/'),
  ('INFIN','Informe de Ensayo','OTRO','conjunto','Plantillas_Informes/Formatos/OTRO/'),
  ('INFIN','Informe Ensayo','OTRO','conjunto','Plantillas_Informes/Formatos/OTRO/'),
  ('STGO1','Certificado de Retardos','OTRO','conjunto','Plantillas_Informes/Formatos/OTRO/'),
  ('IBC01','Planilla respaldo I.V.C.','PLANILLA','conjunto','Plantillas_Informes/Formatos/PLANILLA/'),
  ('IBC01','Planilla Respaldo','PLANILLA','conjunto','Plantillas_Informes/Formatos/PLANILLA/'),
  ('IBC01','Planilla de respaldo','PLANILLA','conjunto','Plantillas_Informes/Formatos/PLANILLA/'),
  ('IBC01','Reporte','PLANILLA','conjunto','Plantillas_Informes/Formatos/PLANILLA/'),
  ('PLAPI','Informe Planilla','PLANILLA','conjunto','Plantillas_Informes/Formatos/PLANILLA/'),
  ('RES01','Planilla de resultados','PLANILLA','conjunto','Plantillas_Informes/Formatos/PLANILLA/'),
  ('RES01','Planilla Resultados','PLANILLA','conjunto','Plantillas_Informes/Formatos/PLANILLA/')
) AS v(repid,nombre,tipo,emision,archivo_ref)
WHERE t.codigo='IDIC'
ON CONFLICT (tenant_id, repid, nombre) DO NOTHING;

-- SELECT tipo, count(*) FROM plantilla_informe GROUP BY tipo ORDER BY 2 DESC;